# Generated by Django 3.1.3 on 2020-12-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='visited',
            field=models.IntegerField(default=0),
        ),
    ]
